/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "uaofdsaxdnfzwaxhvmbx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhb2Zkc2F4ZG5mendheGh2bWJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyMDM0MDMsImV4cCI6MjA4OTc3OTQwM30.nYt3IywIfxx8R3OEK_kvNvW6RQXtifdEPKoi41pbkD0"